import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='h-full'>
      <body className={`${inter.className} h-full`}>
        <Header />
        <main className='md:p-24 h-full bg-gray-dark mb-4'>{children}</main>
      </body>
    </html>
  );
}
